name: Python Cache Demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Prime cache
      - name: Prime cache cache-539c8ce
        id: prime-cache-539c8ce
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: cache-539c8ce

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 5. Show cache result
      - name: Show cache result
        run: |
          if [ "${{ steps.prime-cache-539c8ce.outputs.cache-hit }}" == 'true' ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi
