name: CI with Cache

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create cache folder
        run: mkdir -p ~/.cache/my-dependencies

      - name: prime-cache-539c8ce
        id: cache-step
        uses: actions/cache@v4
        with:
          path: "~/.cache/my-dependencies"
          key: cache-539c8ce
          restore-keys: cache-539c8ce

      - name: Show cache result
        run: echo "Cache hit/miss: ${{ steps.cache-step.outputs.cache-hit }}"

      - name: Install dependencies
        run: echo "dummy dependency" > ~/.cache/my-dependencies/dummy.txt
